import { prisma } from './database';

const SYSTEM_ROLES = [
  {
    name: 'admin',
    displayName: 'Administrateur',
    isSystem: true,
    permissions: ['*'],
  },
  {
    name: 'commercial',
    displayName: 'Commercial',
    isSystem: true,
    permissions: [
      'clients:*',
      'invoices:*',
      'proformas:*',
      'payments:create',
      'payments:read',
      'products:read',
      'suppliers:read',
      'purchases:read',
      'reports:read',
      'dashboard:read',
      'notifications:read',
      'search:read',
      'bank:read',
      'bank:manage',
      'bank:reconcile',
      'bank:import-parse',
      'bank:import-confirm',
      'bank:auto-match',
      'bank:rules',
      'approvals:view_own',
    ],
  },
  {
    name: 'employee',
    displayName: 'Employé',
    isSystem: true,
    permissions: [
      'clients:read',
      'invoices:read',
      'proformas:read',
      'payments:create',
      'payments:read',
      'products:read',
      'dashboard:read',
      'notifications:read',
      'search:read',
      'approvals:view_own',
    ],
  },
  {
    name: 'daf',
    displayName: 'Directeur Administratif et Financier',
    isSystem: true,
    permissions: [
      'clients:*',
      'invoices:*',
      'proformas:*',
      'payments:create',
      'payments:read',
      'payments:delete',
      'products:read',
      'suppliers:read',
      'purchases:*',
      'expenses:*',
      'reports:read',
      'reports:export',
      'dashboard:read',
      'notifications:read',
      'search:read',
      'bank:read',
      'bank:manage',
      'bank:reconcile',
      'bank:import-parse',
      'bank:import-confirm',
      'bank:auto-match',
      'bank:rules',
      'accounting:read',
      'accounting:create',
      'accounting:validate',
      'accounting:close',
      'accounting:export',
      'approvals:approve',
      'approvals:view',
      'approvals:view_own',
    ],
  },
  {
    name: 'dg',
    displayName: 'Directeur Général',
    isSystem: true,
    permissions: [
      'clients:*',
      'invoices:*',
      'proformas:*',
      'payments:create',
      'payments:read',
      'payments:delete',
      'products:*',
      'suppliers:*',
      'purchases:*',
      'expenses:*',
      'stock:read',
      'bank:read',
      'bank:reconcile',
      'accounting:read',
      'accounting:validate',
      'reports:*',
      'dashboard:read',
      'notifications:read',
      'search:read',
      'settings:read',
      'users:read',
      'approvals:approve',
      'approvals:view',
      'approvals:view_own',
    ],
  },
  {
    name: 'dt',
    displayName: 'Directeur Technique',
    isSystem: true,
    permissions: [
      'clients:read',
      'invoices:read',
      'proformas:read',
      'payments:read',
      'products:*',
      'suppliers:*',
      'purchases:*',
      'expenses:read',
      'stock:*',
      'reports:read',
      'dashboard:read',
      'notifications:read',
      'search:read',
      'approvals:approve',
      'approvals:view',
      'approvals:view_own',
    ],
  },
];

export async function seedRoles(): Promise<void> {
  const count = await prisma.role.count();
  if (count > 0) return;

  for (const role of SYSTEM_ROLES) {
    await prisma.role.create({ data: role });
  }

  console.info('[Seed] Rôles système créés :', SYSTEM_ROLES.map((r) => r.name).join(', '));
}
